spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://cloud-and-fog-computing-project-database.postgres.database.azure.com:5432/postgres
    username: AlohaDasha
    password: TuzSeRik087.

  jpa:
    hibernate:
      ddl-auto: create
